const OpenAI = require('openai');
const { Octokit } = require('@octokit/rest');

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
const openai  = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

const owner       = process.env.GITHUB_REPOSITORY.split('/')[0];
const repo        = process.env.GITHUB_REPOSITORY.split('/')[1];
const issueTitle  = process.env.ISSUE_TITLE;
const issueBody   = process.env.ISSUE_BODY || '';
const issueNumber = process.env.ISSUE_NUMBER;

const TARGET_FILE = 'src/converters.js'; // change to your actual file

async function run() {
  console.log(`🔍 Processing issue: ${issueTitle}`);

  // ── 1. Read existing code from the repo ──────────────────────────────────
  const { data: fileData } = await octokit.repos.getContent({
    owner, repo,
    path: TARGET_FILE,
    ref: 'main'
  });
  const existingCode = Buffer.from(fileData.content, 'base64').toString('utf8');
  console.log(`📄 Read existing file: ${TARGET_FILE}`);

  // ── 2. Call OpenAI to generate the updated code ──────────────────────────
  const completion = await openai.chat.completions.create({
    model: 'gpt-4o',
    messages: [
      {
        role: 'system',
        content: `You are an expert software engineer. 
When given a task and an existing code file, you add the required 
function following the exact same coding style and conventions.
Return ONLY the complete updated file content.
No explanations. No markdown code fences. Raw code only.`
      },
      {
        role: 'user',
        content: `Task title: ${issueTitle}

Task description:
${issueBody}

Existing file (${TARGET_FILE}):
${existingCode}

Add the required function and return the complete updated file.`
      }
    ],
    temperature: 0.2  // low temperature = more consistent, predictable code
  });

  const newCode = completion.choices[0].message.content;
  console.log('✅ OpenAI generated code successfully');

  // ── 3. Create a new Git branch ───────────────────────────────────────────
  const branchName = `ai/issue-${issueNumber}`;

  const { data: ref } = await octokit.git.getRef({
    owner, repo,
    ref: 'heads/main'
  });

  await octokit.git.createRef({
    owner, repo,
    ref: `refs/heads/${branchName}`,
    sha: ref.object.sha
  });
  console.log(`🌿 Created branch: ${branchName}`);

  // ── 4. Commit the updated file to the branch ─────────────────────────────
  await octokit.repos.createOrUpdateFileContents({
    owner, repo,
    path: TARGET_FILE,
    message: `feat: #${issueNumber} - ${issueTitle}`,
    content: Buffer.from(newCode).toString('base64'),
    sha: fileData.sha,
    branch: branchName
  });
  console.log('📝 Committed new code to branch');

  // ── 5. Open a Pull Request ───────────────────────────────────────────────
  const { data: pr } = await octokit.pulls.create({
    owner, repo,
    title: `[AI] ${issueTitle}`,
    head: branchName,
    base: 'main',
    body: `## 🤖 AI-generated implementation

**Closes** #${issueNumber}

This PR was automatically generated by the AI agent (GPT-4o) based on the issue description.

> ⚠️ Please review the code carefully before merging.`
  });
  console.log(`🚀 PR opened: ${pr.html_url}`);

  // ── 6. Comment on the issue with the PR link ─────────────────────────────
  await octokit.issues.createComment({
    owner, repo,
    issue_number: parseInt(issueNumber),
    body: `🤖 **AI agent completed!**

A pull request has been opened with the implementation:
👉 ${pr.html_url}

Please review the generated code before merging.`
  });

  console.log('✅ Done! Issue commented with PR link.');
}

run().catch(err => {
  console.error('❌ Error:', err.message);
  process.exit(1);
});