const OpenAI = require('openai');
const { Octokit } = require('@octokit/rest');

// ── Copilot API (same format as OpenAI) ──────────────────────────────────────
const copilot = new OpenAI({
  apiKey: process.env.COPILOT_TOKEN,
  baseURL: 'https://api.githubcopilot.com',
});

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

const owner       = process.env.GITHUB_REPOSITORY.split('/')[0];
const repo        = process.env.GITHUB_REPOSITORY.split('/')[1];
const issueTitle  = process.env.ISSUE_TITLE;
const issueBody   = process.env.ISSUE_BODY || '';
const issueNumber = process.env.ISSUE_NUMBER;

const TARGET_FILE = 'src/converters.js'; // ← change to your file

async function run() {
  console.log(`🔍 Processing: ${issueTitle}`);

  // ── 1. Read existing code from repo ────────────────────────────────────────
  const { data: fileData } = await octokit.repos.getContent({
    owner, repo,
    path: TARGET_FILE,
    ref: 'main'
  });
  const existingCode = Buffer.from(fileData.content, 'base64').toString('utf8');
  console.log(`📄 Read file: ${TARGET_FILE}`);

  // ── 2. Call Copilot API to generate updated code ────────────────────────────
  const completion = await copilot.chat.completions.create({
    model: 'gpt-4o',
    messages: [
      {
        role: 'system',
        content: `You are an expert software engineer using GitHub Copilot.
When given a task and an existing code file, add the required 
function following the exact same coding style and conventions.
Return ONLY the complete updated file content.
No explanations. No markdown fences. Raw code only.`
      },
      {
        role: 'user',
        content: `Task: ${issueTitle}

Description:
${issueBody}

Existing file (${TARGET_FILE}):
${existingCode}

Add the required function and return the complete updated file.`
      }
    ],
    temperature: 0.2
  });

  const newCode = completion.choices[0].message.content;
  console.log('✅ Copilot generated code successfully');

  // ── 3. Create new branch ───────────────────────────────────────────────────
  const branchName = `copilot/issue-${issueNumber}`;

  const { data: ref } = await octokit.git.getRef({
    owner, repo, ref: 'heads/main'
  });

  await octokit.git.createRef({
    owner, repo,
    ref: `refs/heads/${branchName}`,
    sha: ref.object.sha
  });
  console.log(`🌿 Created branch: ${branchName}`);

  // ── 4. Commit updated file ─────────────────────────────────────────────────
  await octokit.repos.createOrUpdateFileContents({
    owner, repo,
    path: TARGET_FILE,
    message: `feat: #${issueNumber} - ${issueTitle}`,
    content: Buffer.from(newCode).toString('base64'),
    sha: fileData.sha,
    branch: branchName
  });
  console.log('📝 Committed code to branch');

  // ── 5. Open Pull Request ───────────────────────────────────────────────────
  const { data: pr } = await octokit.pulls.create({
    owner, repo,
    title: `[Copilot] ${issueTitle}`,
    head: branchName,
    base: 'main',
    body: `## 🤖 Auto-generated by GitHub Copilot

**Closes** #${issueNumber}

This PR was automatically generated by the Copilot AI agent
based on the issue description.

> ⚠️ Please review carefully before merging.`
  });
  console.log(`🚀 PR opened: ${pr.html_url}`);

  // ── 6. Comment on the issue ────────────────────────────────────────────────
  await octokit.issues.createComment({
    owner, repo,
    issue_number: parseInt(issueNumber),
    body: `🤖 **Copilot agent completed!**

A pull request has been opened with the implementation:
👉 ${pr.html_url}

Please review the generated code before merging.`
  });

  console.log('✅ All done!');
}

run().catch(err => {
  console.error('❌ Error:', err.message);
  process.exit(1);
});